In [34]:

import pandas as pd

data_frame = pd.read_csv("../data/delivery.csv")

data_frame.head()

,Order_ID,Distance_km,Weather,Traffic_Level,Time_of_Day,Vehicle_Type,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
0,522,7.93,Windy,Low,Afternoon,Scooter,12,1.0,43
1,738,16.42,Clear,Medium,Evening,Bike,20,2.0,84
2,741,9.52,Foggy,Low,Night,Scooter,28,1.0,59
3,661,7.44,Rainy,Medium,Afternoon,Scooter,5,1.0,37
4,412,19.03,Clear,Low,Morning,Bike,16,5.0,68

In [35]:
data_frame.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Order_ID                1000 non-null   int64
 1   Distance_km             1000 non-null   float64
 2   Weather                 970 non-null    str
 3   Traffic_Level           970 non-null    str
 4   Time_of_Day             970 non-null    str
 5   Vehicle_Type            1000 non-null   str
 6   Preparation_Time_min    1000 non-null   int64
 7   Courier_Experience_yrs  970 non-null    float64
 8   Delivery_Time_min       1000 non-null   int64
dtypes: float64(2), int64(3), str(4)
memory usage: 70.4 KB

In [36]:
import numpy as np 

if 'Order_ID' in df_clean.columns:
    df_clean = df_clean.drop(columns=['Order_ID'])

print(df_clean.columns)

Index(['Distance_km', 'Weather', 'Traffic_Level', 'Time_of_Day',
       'Vehicle_Type', 'Preparation_Time_min', 'Courier_Experience_yrs',
       'Delivery_Time_min'],
      dtype='str')

In [43]:
 

df_clean = data_frame.copy()
# df_clean.head()

string_cols = df_clean.select_dtypes(include=['str']).columns

# print(string_cols)

In [38]:
for col in string_cols:
    df_clean[col] = df_clean[col].astype(str).str.strip()
    df_clean[col] = df_clean[col].replace(["nan","null",''], np.nan, regex= False)

    print(df_clean.columns)

Index(['Order_ID', 'Distance_km', 'Weather', 'Traffic_Level', 'Time_of_Day',
       'Vehicle_Type', 'Preparation_Time_min', 'Courier_Experience_yrs',
       'Delivery_Time_min'],
      dtype='str')
Index(['Order_ID', 'Distance_km', 'Weather', 'Traffic_Level', 'Time_of_Day',
       'Vehicle_Type', 'Preparation_Time_min', 'Courier_Experience_yrs',
       'Delivery_Time_min'],
      dtype='str')
Index(['Order_ID', 'Distance_km', 'Weather', 'Traffic_Level', 'Time_of_Day',
       'Vehicle_Type', 'Preparation_Time_min', 'Courier_Experience_yrs',
       'Delivery_Time_min'],
      dtype='str')
Index(['Order_ID', 'Distance_km', 'Weather', 'Traffic_Level', 'Time_of_Day',
       'Vehicle_Type', 'Preparation_Time_min', 'Courier_Experience_yrs',
       'Delivery_Time_min'],
      dtype='str')

In [39]:
# time_cols = [columns for olumns in df_clean.columns if 'Time_']

print("missing values per colums")
print(data_frame.isnull().sum())

missing values per colums
Order_ID                   0
Distance_km                0
Weather                   30
Traffic_Level             30
Time_of_Day               30
Vehicle_Type               0
Preparation_Time_min       0
Courier_Experience_yrs    30
Delivery_Time_min          0
dtype: int64

In [51]:
av_ex = df_clean['Courier_Experience_yrs'].median()
df_clean['Courier_Experience_yrs'] = df_clean['Courier_Experience_yrs'].fillna(av_ex)

columns_obj = ['Weather', 'Traffic_Level', 'Time_of_Day']

for col in columns_obj:
    mode_val = df_clean[col].mode()[0]
    df_clean[col] = df_clean[col].fillna(mode_val)

In [52]:
print("nombre tota de valeur manquants resytans : ", df_clean.isnull().sum())

nombre tota de valeur manquants resytans :  Order_ID                  0
Distance_km               0
Weather                   0
Traffic_Level             0
Time_of_Day               0
Vehicle_Type              0
Preparation_Time_min      0
Courier_Experience_yrs    0
Delivery_Time_min         0
dtype: int64

In [59]:
num_duplicates = df_clean.duplicated().sum()
print(f"numner of duplicates rows:{num_duplicates}") 

df_clean.describe()

numner of duplicates rows:0

,Order_ID,Distance_km,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,10.059970,16.982000,4.592000,56.732000
std,288.819436,5.696656,7.204553,2.871198,22.070915
min,1.000000,0.590000,5.000000,0.000000,8.000000
25%,250.750000,5.105000,11.000000,2.000000,41.000000
50%,500.500000,10.190000,17.000000,5.000000,55.500000
75%,750.250000,15.017500,23.000000,7.000000,71.000000
max,1000.000000,19.990000,29.000000,9.000000,153.000000

In [ ]:
df_clean = df_clean[df_clean['Delivery_Time_min'] <= 120]
# df_clean.describe()

df_clean.to_csv('../data/df_clean.csv', index=False)

print("cest ca etap 1 ")
print(f"Nombre de commande expoitable conserve : {len(df_clean)}")

,Order_ID,Distance_km,Preparation_Time_min,Courier_Experience_yrs,Delivery_Time_min
count,994.000000,994.000000,994.000000,994.000000,994.000000
mean,500.085513,10.016308,16.959759,4.595573,56.263581
std,289.113713,5.684717,7.206240,2.876340,21.276034
min,1.000000,0.590000,5.000000,0.000000,8.000000
25%,249.250000,5.015000,11.000000,2.000000,41.000000
50%,501.500000,10.150000,17.000000,5.000000,55.000000
75%,749.750000,14.890000,23.000000,7.000000,71.000000
max,1000.000000,19.990000,29.000000,9.000000,116.000000